### ISSUE TITLE
Cannot be opened in Firefox

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/starcounter-debug-aid#41]
### Steps to reproduce
Open up any starcounter app in Firefox
Press _Ctrl_ + _§_

### Expected result
starcounter-debug-aid should be opened

### Actual result
nothing happens

### Browsers affected

- [ ] Chrome
- [x ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

**Comment by ubbeK** [comment]
We should add a smoke test which simply opens the `starcounter-debug-aid` in Kitchensink.

WDYT @warpech

**Comment by warpech** [comment]
I have American keyboard layout, and for me Starcounter Debug Aid opens OK in Firefox.

JavaScript key bindings are crazy: http://stackoverflow.com/questions/27861122/how-do-international-keyboards-work-with-javascript-keyboard-events

Have you tried other buttons? It might be CTRL + ` or CTRL + ~, depending on the keyboard. 

Turns out that in web apps, choice of any character that is not in range A-Z, 0-9 is asking for trouble. The best idea would be to add another keyboard hotkey that triggers Starcounter Debug Aid. 

Shift + ESC seems quite consistently supported and universally available.

It is a good idea regarding the test.

**Comment by ubbeK** [comment]
You are right. When swedish-keyboard layout is selected in Windows, then `Ctrl + ´` (Ctrl + key left of backspace) opens the `starcounter-debug-aid`. And for english-keyboard layout, `Ctrl + §` (Ctrl + key left of 1) opens it up.

**Comment by warpech** [comment]
I guess that for our users the explanation: *To start Starcounter Debug Aid, press CTRL + that key left of 1* sounds silly.

As a user of Swedish keyboard layout, would you feel comfortable with the description to press CTRL + `? Is the ` key located in some convenient place? 

Because perhaps we can actually detect it properly if we move it from `keydown` event listener to `keypress`. See:

- http://help.dottoro.com/ljlwfxum.php
- http://unixpapa.com/js/key.html

Btw. on my American keyboard there is no § character.

**Comment by ubbeK** [comment]
Well, there are two `Ctrl`-keys so it would feel like pressing `Shift + F12` in VisualStudio for finding all references. I guess that is OK.

**Comment by ubbeK** [comment]
I just realized that in order to press `?` on a swedish keyboard, one would have to press `Shift and +` (key to right of 9). So wouldn't this mean that keys `Ctrl and Shift and +` should be pressed to open the debug aid?

**Comment by tomalec** [comment]
(just to note, that some day it could be slightly better to deal with https://www.w3.org/TR/uievents-code/ https://www.w3.org/TR/uievents-key/)

**Comment by alshakero** [comment]
Closing as no longer relevant.
